package com.oil.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.oil.Bean.Order;
import com.oil.Bean.XiaoshourenBean;
import com.oil.Bean.ZhiwenBean;

import com.oil.greendao.OrderDao;
import com.oil.greendao.XiaoshourenBeanDao;
import com.oil.greendao.ZhiwenBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig orderDaoConfig;
    private final DaoConfig xiaoshourenBeanDaoConfig;
    private final DaoConfig zhiwenBeanDaoConfig;

    private final OrderDao orderDao;
    private final XiaoshourenBeanDao xiaoshourenBeanDao;
    private final ZhiwenBeanDao zhiwenBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        xiaoshourenBeanDaoConfig = daoConfigMap.get(XiaoshourenBeanDao.class).clone();
        xiaoshourenBeanDaoConfig.initIdentityScope(type);

        zhiwenBeanDaoConfig = daoConfigMap.get(ZhiwenBeanDao.class).clone();
        zhiwenBeanDaoConfig.initIdentityScope(type);

        orderDao = new OrderDao(orderDaoConfig, this);
        xiaoshourenBeanDao = new XiaoshourenBeanDao(xiaoshourenBeanDaoConfig, this);
        zhiwenBeanDao = new ZhiwenBeanDao(zhiwenBeanDaoConfig, this);

        registerDao(Order.class, orderDao);
        registerDao(XiaoshourenBean.class, xiaoshourenBeanDao);
        registerDao(ZhiwenBean.class, zhiwenBeanDao);
    }
    
    public void clear() {
        orderDaoConfig.clearIdentityScope();
        xiaoshourenBeanDaoConfig.clearIdentityScope();
        zhiwenBeanDaoConfig.clearIdentityScope();
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

    public XiaoshourenBeanDao getXiaoshourenBeanDao() {
        return xiaoshourenBeanDao;
    }

    public ZhiwenBeanDao getZhiwenBeanDao() {
        return zhiwenBeanDao;
    }

}
