package com.oil.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.oil.Bean.XiaoshourenBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "XIAOSHOUREN_BEAN".
*/
public class XiaoshourenBeanDao extends AbstractDao<XiaoshourenBean, Long> {

    public static final String TABLENAME = "XIAOSHOUREN_BEAN";

    /**
     * Properties of entity XiaoshourenBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property CardId = new Property(2, String.class, "cardId", false, "CARD_ID");
        public final static Property FingerprintId = new Property(3, int.class, "fingerprintId", false, "FINGERPRINT_ID");
    }


    public XiaoshourenBeanDao(DaoConfig config) {
        super(config);
    }
    
    public XiaoshourenBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"XIAOSHOUREN_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"CARD_ID\" TEXT," + // 2: cardId
                "\"FINGERPRINT_ID\" INTEGER NOT NULL );"); // 3: fingerprintId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"XIAOSHOUREN_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, XiaoshourenBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String cardId = entity.getCardId();
        if (cardId != null) {
            stmt.bindString(3, cardId);
        }
        stmt.bindLong(4, entity.getFingerprintId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, XiaoshourenBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String cardId = entity.getCardId();
        if (cardId != null) {
            stmt.bindString(3, cardId);
        }
        stmt.bindLong(4, entity.getFingerprintId());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public XiaoshourenBean readEntity(Cursor cursor, int offset) {
        XiaoshourenBean entity = new XiaoshourenBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // cardId
            cursor.getInt(offset + 3) // fingerprintId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, XiaoshourenBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCardId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setFingerprintId(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(XiaoshourenBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(XiaoshourenBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(XiaoshourenBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
